server:
  port: ${PORT:8080}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true

jwt:
  secret: d9cbf1ef-98fc-4e94-be4b-e3123b7698f5
  expiration: 86400000


