server:
  port: 8082

spring:
  application:
    name: history-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  graphql:
    schema:
      locations: classpath:graphql/
  jackson:
    serialization:
      write-dates-as-timestamps: false

feign:
  client:
    config:
      default:
        loggerLevel: basic

auth:
  service:
    base-url: http://localhost:8080