server:
  port: 8081

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue: appointments.notification
  exchange: appointments.exchange
  routingkey: appointments.notify


auth:
  service:
    base-url: ${AUTH_SERVICE_URL:http://localhost:8080}

