server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

jwt:
  secret: d9cbf1ef-98fc-4e94-be4b-e3123b7698f5

auth:
  service:
    base-url: http://localhost:8080

